#!/usr/bin/env python3
import re
import sys
from collections import OrderedDict


# GIVEN A FILE (LIKE THAT GENERATED BY generating_harness.py), PRINT A LIST OF MESSAGE TYPES 
def extract_msg_types(file_path):
    # Match patterns like: elif msg_type == 'CAMERA_SETTINGS'
    pattern = re.compile(r"""elif\s+msg_type\s*==\s*   # elif msg_type ==
                             ['"]([^'"]+)['"]           # 'MSG_TYPE' or "MSG_TYPE"
                          """, re.VERBOSE)
    seen = OrderedDict()
    with open(file_path, 'r') as f:
        for line in f:
            m = pattern.search(line)
            if m:
                seen[m.group(1)] = None
    return list(seen.keys())

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <path_to_script>")
        sys.exit(1)
    file_path = sys.argv[1]
    msg_types = extract_msg_types(file_path)
    print(msg_types)

if __name__ == "__main__":
    main()
