import ctypes

SEED = 45
MIN, MAX, RAND = 0, 1, 2

TYPE_RANGES = {
    'uint64_t': [0, 2**64 - 1],  # unsigned 64-bit integer: 0 to 18,446,744,073,709,551,615
    'int64_t': [-2**63, 2**63 - 1],  # signed 64-bit integer: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
    'uint32_t': [0, 2**32 - 1],  # unsigned 32-bit integer: 0 to 4,294,967,295
    'int32_t': [-2**31, 2**31 - 1],  # signed 32-bit integer: -2,147,483,648 to 2,147,483,647
    'uint16_t': [0, 2**16 - 1],  # unsigned 16-bit integer: 0 to 65,535
    'int16_t': [-2**15, 2**15 - 1],  # signed 16-bit integer: -32,768 to 32,767
    'uint8_t': [0, 2**8 - 1],  # unsigned 8-bit integer: 0 to 255
    'int8_t': [-2**7, 2**7 - 1],  # signed 8-bit integer: -128 to 127
    'float' : [-3.4028235e38, 3.4028235e38], # 32-bit floating point (IEEE 754): approx -3.4e38 to 3.4e38
    'double': [-1.7976931348623157e308, 1.7976931348623157e308]  # 64-bit floating point (IEEE 754): approx -1.8e308 to 1.8e308
}


MESSAGE_TYPES = ['SYSTEM_TIME', 'PING', 'CHANGE_OPERATOR_CONTROL', 'CHANGE_OPERATOR_CONTROL_ACK', 'AUTH_KEY', 'SET_MODE', 'PARAM_REQUEST_READ', 'PARAM_REQUEST_LIST', 'PARAM_VALUE', 'PARAM_SET', 'GPS_RAW_INT', 'GPS_STATUS', 'SCALED_IMU', 'RAW_IMU', 'RAW_PRESSURE', 'SCALED_PRESSURE', 'ATTITUDE', 'ATTITUDE_QUATERNION', 'LOCAL_POSITION_NED', 'GLOBAL_POSITION_INT', 'RC_CHANNELS_SCALED', 'RC_CHANNELS_RAW', 'SERVO_OUTPUT_RAW', 'MISSION_REQUEST_PARTIAL_LIST', 'MISSION_WRITE_PARTIAL_LIST', 'MISSION_ITEM', 'MISSION_REQUEST', 'MISSION_SET_CURRENT', 'MISSION_CURRENT', 'MISSION_REQUEST_LIST', 'MISSION_COUNT', 'MISSION_CLEAR_ALL', 'MISSION_ITEM_REACHED', 'MISSION_ACK', 'SET_GPS_GLOBAL_ORIGIN', 'GPS_GLOBAL_ORIGIN', 'PARAM_MAP_RC', 'MISSION_REQUEST_INT', 'SAFETY_SET_ALLOWED_AREA', 'SAFETY_ALLOWED_AREA', 'ATTITUDE_QUATERNION_COV', 'NAV_CONTROLLER_OUTPUT', 'GLOBAL_POSITION_INT_COV', 'LOCAL_POSITION_NED_COV', 'RC_CHANNELS', 'REQUEST_DATA_STREAM', 'DATA_STREAM', 'MANUAL_CONTROL', 'RC_CHANNELS_OVERRIDE', 'MISSION_ITEM_INT', 'VFR_HUD', 'COMMAND_INT', 'COMMAND_LONG', 'COMMAND_ACK', 'MANUAL_SETPOINT', 'SET_ATTITUDE_TARGET', 'ATTITUDE_TARGET', 'SET_POSITION_TARGET_LOCAL_NED', 'POSITION_TARGET_LOCAL_NED', 'SET_POSITION_TARGET_GLOBAL_INT', 'POSITION_TARGET_GLOBAL_INT', 'LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET', 'HIL_STATE', 'HIL_CONTROLS', 'HIL_RC_INPUTS_RAW', 'HIL_ACTUATOR_CONTROLS', 'OPTICAL_FLOW', 'GLOBAL_VISION_POSITION_ESTIMATE', 'VISION_POSITION_ESTIMATE', 'VISION_SPEED_ESTIMATE', 'VICON_POSITION_ESTIMATE', 'HIGHRES_IMU', 'OPTICAL_FLOW_RAD', 'HIL_SENSOR', 'SIM_STATE', 'RADIO_STATUS', 'FILE_TRANSFER_PROTOCOL', 'TIMESYNC', 'CAMERA_TRIGGER', 'HIL_GPS', 'HIL_OPTICAL_FLOW', 'HIL_STATE_QUATERNION', 'SCALED_IMU2', 'LOG_REQUEST_LIST', 'LOG_ENTRY', 'LOG_REQUEST_DATA', 'LOG_DATA', 'LOG_ERASE', 'LOG_REQUEST_END', 'GPS_INJECT_DATA', 'GPS2_RAW', 'POWER_STATUS', 'SERIAL_CONTROL', 'GPS_RTK', 'GPS2_RTK', 'SCALED_IMU3', 'DATA_TRANSMISSION_HANDSHAKE', 'ENCAPSULATED_DATA', 'DISTANCE_SENSOR', 'TERRAIN_REQUEST', 'TERRAIN_DATA', 'TERRAIN_CHECK', 'TERRAIN_REPORT', 'SCALED_PRESSURE2', 'ATT_POS_MOCAP', 'SET_ACTUATOR_CONTROL_TARGET', 'ACTUATOR_CONTROL_TARGET', 'ALTITUDE', 'RESOURCE_REQUEST', 'SCALED_PRESSURE3', 'FOLLOW_TARGET', 'CONTROL_SYSTEM_STATE', 'BATTERY_STATUS', 'AUTOPILOT_VERSION', 'LANDING_TARGET', 'FENCE_STATUS', 'MAG_CAL_REPORT', 'EFI_STATUS', 'ESTIMATOR_STATUS', 'WIND_COV', 'GPS_INPUT', 'GPS_RTCM_DATA', 'HIGH_LATENCY', 'HIGH_LATENCY2', 'VIBRATION', 'HOME_POSITION', 'SET_HOME_POSITION', 'MESSAGE_INTERVAL', 'EXTENDED_SYS_STATE', 'ADSB_VEHICLE', 'COLLISION', 'V2_EXTENSION', 'MEMORY_VECT', 'DEBUG_VECT', 'NAMED_VALUE_FLOAT', 'NAMED_VALUE_INT', 'STATUSTEXT', 'DEBUG', 'SETUP_SIGNING', 'BUTTON_CHANGE', 'PLAY_TUNE', 'CAMERA_INFORMATION', 'CAMERA_SETTINGS', 'STORAGE_INFORMATION', 'CAMERA_CAPTURE_STATUS', 'CAMERA_IMAGE_CAPTURED', 'FLIGHT_INFORMATION', 'MOUNT_ORIENTATION', 'LOGGING_DATA', 'LOGGING_DATA_ACKED', 'LOGGING_ACK', 'VIDEO_STREAM_INFORMATION', 'VIDEO_STREAM_STATUS', 'CAMERA_FOV_STATUS', 'CAMERA_TRACKING_IMAGE_STATUS', 'CAMERA_TRACKING_GEO_STATUS', 'CAMERA_THERMAL_RANGE', 'GIMBAL_MANAGER_INFORMATION', 'GIMBAL_MANAGER_STATUS', 'GIMBAL_MANAGER_SET_ATTITUDE', 'GIMBAL_DEVICE_INFORMATION', 'GIMBAL_DEVICE_SET_ATTITUDE', 'GIMBAL_DEVICE_ATTITUDE_STATUS', 'AUTOPILOT_STATE_FOR_GIMBAL_DEVICE', 'GIMBAL_MANAGER_SET_PITCHYAW', 'GIMBAL_MANAGER_SET_MANUAL_CONTROL', 'WIFI_CONFIG_AP', 'AIS_VESSEL', 'UAVCAN_NODE_STATUS', 'UAVCAN_NODE_INFO', 'PARAM_EXT_REQUEST_READ', 'PARAM_EXT_REQUEST_LIST', 'PARAM_EXT_VALUE', 'PARAM_EXT_SET', 'PARAM_EXT_ACK', 'OBSTACLE_DISTANCE', 'ODOMETRY', 'TRAJECTORY_REPRESENTATION_WAYPOINTS', 'TRAJECTORY_REPRESENTATION_BEZIER', 'CELLULAR_STATUS', 'ISBD_LINK_STATUS', 'CELLULAR_CONFIG', 'RAW_RPM', 'UTM_GLOBAL_POSITION', 'DEBUG_FLOAT_ARRAY', 'SMART_BATTERY_INFO', 'FUEL_STATUS', 'BATTERY_INFO', 'GENERATOR_STATUS', 'ACTUATOR_OUTPUT_STATUS', 'TIME_ESTIMATE_TO_TARGET', 'TUNNEL', 'CAN_FRAME', 'COMPONENT_INFORMATION', 'COMPONENT_INFORMATION_BASIC', 'PLAY_TUNE_V2', 'SUPPORTED_TUNES', 'AVAILABLE_MODES', 'CURRENT_MODE', 'AVAILABLE_MODES_MONITOR', 'ILLUMINATOR_STATUS', 'CANFD_FRAME', 'CAN_FILTER_MODIFY', 'WHEEL_DISTANCE', 'WINCH_STATUS', 'OPEN_DRONE_ID_BASIC_ID', 'OPEN_DRONE_ID_LOCATION', 'OPEN_DRONE_ID_AUTHENTICATION', 'OPEN_DRONE_ID_SELF_ID', 'OPEN_DRONE_ID_SYSTEM', 'OPEN_DRONE_ID_OPERATOR_ID', 'OPEN_DRONE_ID_MESSAGE_PACK', 'OPEN_DRONE_ID_ARM_STATUS', 'OPEN_DRONE_ID_SYSTEM_UPDATE', 'HYGROMETER_SENSOR']

# MESSAGE_TYPES = [
#     'SYS_STATUS', 'SYSTEM_TIME', 'PING', 'CHANGE_OPERATOR_CONTROL',
#     'CHANGE_OPERATOR_CONTROL_ACK', 'AUTH_KEY',
#     'SET_MODE', 'PARAM_REQUEST_READ', 'PARAM_REQUEST_LIST',
#     'PARAM_VALUE', 'PARAM_SET', 'GPS_RAW_INT', 'GPS_STATUS',
#     'SCALED_IMU', 'RAW_IMU', 'RAW_PRESSURE', 'SCALED_PRESSURE',
#     'ATTITUDE', 'ATTITUDE_QUATERNION', 'LOCAL_POSITION_NED',
#     'GLOBAL_POSITION_INT', 'RC_CHANNELS_SCALED', 'RC_CHANNELS_RAW',
#     'SERVO_OUTPUT_RAW', 'MISSION_REQUEST_PARTIAL_LIST',
#     'MISSION_WRITE_PARTIAL_LIST', 'MISSION_ITEM', 'MISSION_REQUEST',
#     'MISSION_SET_CURRENT', 'MISSION_CURRENT', 'MISSION_REQUEST_LIST',
#     'MISSION_COUNT', 'MISSION_CLEAR_ALL', 'MISSION_ITEM_REACHED',
#     'MISSION_ACK', 'SET_GPS_GLOBAL_ORIGIN', 'GPS_GLOBAL_ORIGIN',
#     'PARAM_MAP_RC', 'MISSION_REQUEST_INT', 'SAFETY_SET_ALLOWED_AREA',
#     'SAFETY_ALLOWED_AREA', 'ATTITUDE_QUATERNION_COV',
#     'NAV_CONTROLLER_OUTPUT', 'GLOBAL_POSITION_INT_COV',
#     'LOCAL_POSITION_NED_COV', 'RC_CHANNELS', 'REQUEST_DATA_STREAM',
#     'DATA_STREAM', 'MANUAL_CONTROL', 'RC_CHANNELS_OVERRIDE',
#     'MISSION_ITEM_INT', 'VFR_HUD', 'COMMAND_INT', 'COMMAND_LONG', 'COMMAND_ACK', 'MANUAL_SETPOINT',
#     'SET_ATTITUDE_TARGET', 'ATTITUDE_TARGET', 'SET_POSITION_TARGET_LOCAL_NED',
#     'POSITION_TARGET_LOCAL_NED', 'SET_POSITION_TARGET_GLOBAL_INT',
#     'POSITION_TARGET_GLOBAL_INT', 'LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET',
#     'HIL_STATE', 'HIL_CONTROLS', 'HIL_RC_INPUTS_RAW', 'HIL_ACTUATOR_CONTROLS',
#     'OPTICAL_FLOW', 'GLOBAL_VISION_POSITION_ESTIMATE', 'VISION_POSITION_ESTIMATE',
#     'VISION_SPEED_ESTIMATE', 'VICON_POSITION_ESTIMATE', 'HIGHRES_IMU',
#     'OPTICAL_FLOW_RAD', 'HIL_SENSOR', 'SIM_STATE', 'RADIO_STATUS',
#     'FILE_TRANSFER_PROTOCOL', 'TIMESYNC', 'CAMERA_TRIGGER', 'HIL_GPS',
#     'HIL_OPTICAL_FLOW', 'HIL_STATE_QUATERNION', 'SCALED_IMU2', 'LOG_REQUEST_LIST',
#     'LOG_ENTRY', 'LOG_REQUEST_DATA', 'LOG_DATA', 'LOG_ERASE', 'LOG_REQUEST_END',
#     'GPS_INJECT_DATA', 'GPS2_RAW', 'POWER_STATUS', 'SERIAL_CONTROL', 'GPS_RTK',
#     'GPS2_RTK', 'SCALED_IMU3', 'DATA_TRANSMISSION_HANDSHAKE', 'ENCAPSULATED_DATA',
#     'DISTANCE_SENSOR', 'TERRAIN_REQUEST', 'TERRAIN_DATA', 'TERRAIN_CHECK',
#     'TERRAIN_REPORT', 'SCALED_PRESSURE2', 'ATT_POS_MOCAP',
#     'SET_ACTUATOR_CONTROL_TARGET', 'ACTUATOR_CONTROL_TARGET', 'ALTITUDE',
#     'RESOURCE_REQUEST', 'SCALED_PRESSURE3', 'FOLLOW_TARGET',
#     'CONTROL_SYSTEM_STATE', 'BATTERY_STATUS', 'AUTOPILOT_VERSION',
#     'LANDING_TARGET', 'FENCE_STATUS', 'MAG_CAL_REPORT', 'EFI_STATUS', 'ESTIMATOR_STATUS',
#     'WIND_COV', 'GPS_INPUT', 'GPS_RTCM_DATA', 'HIGH_LATENCY', 'HIGH_LATENCY2',
#     'VIBRATION', 'HOME_POSITION', 'SET_HOME_POSITION', 'MESSAGE_INTERVAL',
#     'EXTENDED_SYS_STATE', 'ADSB_VEHICLE', 'COLLISION', 'V2_EXTENSION',
#     'MEMORY_VECT', 'DEBUG_VECT', 'NAMED_VALUE_FLOAT', 'NAMED_VALUE_INT',
#     'STATUSTEXT', 'DEBUG'
# ]
